-- pgTAP placeholder for CACH-0029.
-- skip: the current Supabase schema in this repo is documented in AGENTS.md,
-- but there are no versioned app migrations for profiles/projects/events/incomes/expenses yet.
-- Without those migrations, RLS tests for payments cannot be reproduced from a clean db.
--
-- Target coverage once migrations are versioned:
-- - tests.rls_enabled('public')
-- - user A cannot SELECT rows owned by user B
-- - user A cannot UPDATE paid_date rows owned by user B
-- - user A can SELECT/UPDATE own payment rows
